apps/blogs/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<str:slug>/', BlogDetailView.as_view(), name='detail'),
]

apps/likes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('switch_like/', views.switch_like, name='switch_like'),
]

iblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # 第三方的应用
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),

    # 开发的应用
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('index/', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blogs/models.py
from collections import defaultdict

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.conf import settings
from django.shortcuts import reverse

from uuslug import slugify

from users.models import User
from likes.models import Like
# Create your models here.


class TagQuerySet(models.query.QuerySet):
    """自定义标签QuerySet, 提高模型的可用性"""
    def names(self):
        return [tag.name for tag in self.all()]


class Tag(models.Model):
    name = models.CharField('标签', max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', related_name='tag_author', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)
    objects = TagQuerySet.as_manager()

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField('分类', max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='type_author', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogQuerySet(models.query.QuerySet):
    """自定义博客QuerySet, 提高模型的可用性"""
    def get_publish(self, tag=None):
        return self.filter(status='publish', tags__name=tag) if tag else self.filter(status='publish')

    def get_tags_cloud(self):
        """统计所有已发布的博客中，每一个标签的数量(大于0的)"""
        tag_dict = defaultdict(int)
        for obj in self.get_publish():
            for tag in obj.tags.all().names():
                tag_dict[tag] += 1
        return tag_dict.items()


class Blog(models.Model):
    STATUS = (('publish', '发布'), ('draft', '草稿'), ('delete', '删除'), ('diary', '日记'))
    title = models.CharField('标题', max_length=255, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_author', verbose_name='作者', null=True, blank=True, on_delete=models.SET_NULL)
    image = models.ImageField('图片', upload_to='blog_imgs/%Y/%m/%d/', null=True, blank=True)
    slug = models.SlugField('(URL)别名', max_length=255, null=True, blank=True)
    status = models.CharField('状态', choices=STATUS, default='draft', max_length=10)
    content = models.TextField('内容')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    type = models.ForeignKey(Type, related_name='blog_type', verbose_name='分类', null=True, blank=True, on_delete=models.SET_NULL)
    likes = GenericRelation(Like, verbose_name='点赞情况')  # 通过GenericRelation关联到Like表，不是实际的字段
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)
    objects = BlogQuerySet.as_manager()

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super().save()

    def get_like_num(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'slug': self.slug})

apps/blogs/views.py
from django.views.generic import ListView, DetailView

from .models import Blog, Tag
# Create your views here.


class TagCloudMixin:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'tags_cloud': Blog.objects.get_tags_cloud(),
            'blog_publish_counted': Blog.objects.get_publish().count()
        })
        return context


class BlogListView(TagCloudMixin, ListView):
    """已发布的文章列表"""
    model = Blog
    paginate_by = 5
    context_object_name = 'blogs'
    template_name = 'blogs/blogs_list.html'
    tag = None

    def get_queryset(self):
        return Blog.objects.get_publish(tag=self.tag) if self.get_tag() else Blog.objects.get_publish()

    def get_tag(self):
        self.tag = self.request.GET.dict().get('tag')
        return self.tag if self.tag in Tag.objects.names() else None

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class BlogDetailView(TagCloudMixin, DetailView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blogs/blogs_detail.html'
    is_like = False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_like'] = self.get_is_like()
        return context

    def get_is_like(self):
        if self.request.user.is_authenticated:
            like = self.object.likes.filter(user=self.request.user)
            if like.exists():
                self.is_like = True
        return self.is_like

templates/blogs/blogs_detail.html
{% extends 'base.html' %}
{% load staticfiles thumbnail %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'assets/css/highlight.min.css' %}">
{% endblock %}

{% block title %}博客详情{% endblock %}
{% block bread_crumbs %}
    <div class="breadcrumbs-area clearfix">
        <h4 class="page-title pull-left">AhernBlog</h4>
         <ul class="breadcrumbs pull-left">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="{% url 'blogs:list' %}">博客</a></li>
            <li><span>{{ blog.title }}</span></li>
        </ul>
    </div>
{% endblock %}
{% block main %}
    <div class="row">
        <!-- seo fact area start -->
        <div class="col-lg-8" blog-id="{{ blog.id }}">
            <div class="row">
                <div class="col-md-6 mt-5 mb-3">
                    <div class="card">
                        <div class="seo-fact sbg1">
                            <div class="p-4 d-flex justify-content-between align-items-center">
                                <div class="seofct-icon"><i class="ti-thumb-up"></i> Likes</div>
                                <h2>0</h2>
                            </div>
                            <canvas id="seolinechart1" height="1"></canvas>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mt-md-5 mb-3">
                    <div class="card">
                        <div class="seo-fact sbg2">
                            <div class="p-4 d-flex justify-content-between align-items-center">
                                <div class="seofct-icon"><i class="ti-share"></i> Share</div>
                                <h2>0</h2>
                            </div>
                            <canvas id="seolinechart2" height="1"></canvas>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-3 mb-lg-0">
                    <div class="card">
                        <div class="seo-fact sbg3">
                            <div class="p-4 d-flex justify-content-between align-items-center">
                                <div class="seofct-icon">Impressions</div>
                                <canvas id="seolinechart3" height="60"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="seo-fact sbg4">
                            <div class="p-4 d-flex justify-content-between align-items-center">
                                <div class="seofct-icon">New Users</div>
                                <canvas id="seolinechart4" height="60"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Title -->
            <h2 class="text-center mt-5">{{ blog.title|title }}</h2>
            <!-- Author -->
            <p class="text-left mt-2 mb-2">
                <a href="#">{{ blog.user.name }}</a>
                发表于{{ blog.created_at }}
            </p>
            <div class="interaction" id="interaction">
                <span class="fa fa-tags mr-2">
                    {% for tag in blog.tags.all %}
                        <a href="{% url 'blogs:list' %}?tag={{ tag }}" class="mx-1">{{ tag }}</a>
                    {% endfor %}
                </span>
                <a href="javascipt:void(0);" class="like">
                    {% if is_like %}
                        <i class="heart fa fa-heart" aria-hidden="true"></i>
                    {% else %}
                        <i class="heart fa fa-heart-o" aria-hidden="true"></i>
                    {% endif %}
                    <span class="like-count ml-1">{{ blog.get_like_num }}</span>
                </a>
            </div>
            <hr>
            <!-- 文章图片 -->
            {% thumbnail blog.image "1920x1080" as im %}
                <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
            {% empty %}
                <img class="img-fluid rounded" src="http://placehold.it/1920x1080" alt="Card Image">
            {% endthumbnail %}
            <hr>
            <!-- Post Content -->
            <p class="card-text">{{ blog.content|safe }}</p>
            <hr>
        </div>
        <!-- seo fact area end -->
        <div class="col-lg-4">
            <!-- 云标签 -->
            <div class="card mt-5">
                <h5 class="card-header">云标签</h5>
                <div class="card-body">
                    <a href="{% url 'blogs:list' %}"><span class="badge badge-info">全部({{ blog_publish_counted }})</span></a>
                    {% for tag, count in tags_cloud %}
                        <a href="{% url 'blogs:list' %}?tag={{ tag }}"><span class="badge badge-info">{{ tag }}({{ count }})</span></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'assets/js/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad()</script>
    <script>
        function switch_like(object_type, object_id){
            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'likes:switch_like' %}",
                data:{'object_type': object_type, 'object_id': object_id},
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    if (!data['msg']) {
                        window.location.href="{% url 'account_login' %}?next={{ blog.get_absolute_url }}";
                    }
                    $(".like .like-count").text(data['like_num']);
                    console.log(data['msg']);
                    if (data['is_like'] == true) {
                        $(".like .heart").removeClass("fa fa-heart-o");
                        $(".like .heart").addClass("fa fa-heart");
                    } else {
                        $(".like .heart").removeClass("fa fa-heart");
                        $(".like .heart").addClass("fa fa-heart-o");
                    }
                },
                error: function (xhr) {
                    console.log(xhr);
                },
            });
            return false;
        }
        $('.like').on('click', function(){
            switch_like('blog', {{ blog.id }});
        });
    </script>

{% endblock %}

templates/blogs/blogs_list.html
{% extends 'base.html' %}
{% load staticfiles thumbnail humanize %}

{% block extra_css %}
{% endblock %}
{% block title %}博客列表{% endblock %}
{% block bread_crumbs %}
    <div class="breadcrumbs-area clearfix">
        <h4 class="page-title pull-left">AhernBlog</h4>
        <ul class="breadcrumbs pull-left">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><span>博客</span></li>
        </ul>
    </div>
{% endblock %}
{% block main %}
    <div class="row">
        <div class="card-area col-md-8 col-xs-12">
            <!-- 循环遍历博客列表 -->
            {% for blog in blogs %}
                <div class="mt-5" blog-id="{{ blog.id }}">
                    <div class="card card-bordered">
                        {% thumbnail blog.image "1920x1080" as img %}
                            <img class="card-img-top img-fluid" src="{{ img.url }}" alt="image">
                        {% empty %}
                            <img class="card-img-top img-fluid" src="http://placehold.it/1920x1080" alt="image">
                        {% endthumbnail %}

                        <div class="card-body">
                            <h5 class="title">{{ blog.title|title }}</h5>
                            <p class="card-text">{{ blog.content|truncatechars:'250' }}</p>
                            <div>
                                <a href="{% url 'blogs:detail' blog.slug %}" class="btn-sm btn-primary mr-3">阅读全文</a>
                                <a href="">{{ blog.user.name }}</a>发表于{{ blog.created_at|naturaltime }}
                            </div>
                        </div>
                        <div class="card-footer text-muted">
                            <div class="interaction" id="interaction">
                                <span class="fa fa-tags mr-2">
                                    {% for tag in blog.tags.all %}
                                        <a href="{% url 'blogs:list' %}?tag={{ tag }}" class="mx-1">{{ tag }}</a>
                                    {% endfor %}
                                </span>
                                <i class="heart fa fa-heart-o" aria-hidden="true"><span class="like-count ml-2">{{ blog.get_like_num }}</span></i>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <h4 class="no-data">作者还没有更新文章!</h4>
            {% endfor %}
            {% include 'pagination.html' %}
        </div>

        <div class="col-md-4">
            <!-- 云标签 -->
            <div class="card mt-5">
                <h5 class="card-header">云标签</h5>
                <div class="card-body">
                    <a href="{% url 'blogs:list' %}"><span
                            class="badge badge-info">全部({{ blog_publish_counted }})</span></a>
                    {% for tag, count in tags_cloud %}
                        <a href="{{ blog.get_absolute_url }}?tag={{ tag }}"><span
                                class="badge badge-info">{{ tag }}({{ count }})</span></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
{% endblock %}