apps/blogs/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<str:slug>/', BlogDetailView.as_view(), name='detail'),
]

iblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # 第三方的应用
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),

    # 开发的应用
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('index/', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/search/search.html
{% extends 'base.html' %}
{% load static humanize thumbnail %}

{% block extra_css %}{% endblock %}

{% block title %}搜索{% endblock %}

{% block bread_crumbs %}
    <div class="breadcrumbs-area clearfix">
        <h4 class="page-title pull-left">AhernBlog</h4>
        <ul class="breadcrumbs pull-left">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><span>搜索结果</span></li>
        </ul>
    </div>
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-4 mt-3">
            <div class="list-group" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active" id="list-blog-list" data-toggle="list"
                   href="#list-blog"
                   role="tab" aria-controls="articles">文章</a>
            </div>
        </div>
        <div class="col-md-8 mt-3">
            <div class="tab-content" id="nav-tabContent">
                {% for result in page.object_list %}
                    {% if result.app_label == "blogs" %}
                        <div class="tab-pane fade show active" id="list-blog" role="tabpanel"
                             aria-labelledby="list-blog-list">
                            <div class="card mb-4">
                                {% thumbnail result.object.image "1920x1080" as im %}
                                    <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
                                {% empty %}
                                    <img class="card-img-top" src="http://placehold.it/1920x1080" alt="没有图片">
                                {% endthumbnail %}
                                <div class="card-body">
                                    <h2 class="card-title"><a href="{% url 'blogs:detail' result.object.slug %}">
                                        {{ result.object.title|title }}</a></h2>
                                    <p class="card-text">{{ result.object.content|truncatechars:250|safe }}</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <h4 class="no-data">没有您要的搜索结果，换个关键字试试</h4>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}{% endblock %}