apps/blogs/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<str:slug>/', BlogDetailView.as_view(), name='detail'),
]

iblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # django admin
    path('admin/', admin.site.urls),

    # 第三方的应用
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),

    # 开发的应用
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('index/', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blogs/models.py
from collections import defaultdict

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.conf import settings
from django.shortcuts import reverse

from uuslug import slugify

from users.models import User
from likes.models import Like
# Create your models here.


class TagQuerySet(models.query.QuerySet):
    """自定义标签QuerySet, 提高模型的可用性"""
    def names(self):
        return [tag.name for tag in self.all()]


class Tag(models.Model):
    name = models.CharField('标签', max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', related_name='tag_author', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)
    objects = TagQuerySet.as_manager()

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField('分类', max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='type_author', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogQuerySet(models.query.QuerySet):
    """自定义博客QuerySet, 提高模型的可用性"""
    def get_publish(self, tag=None):
        return self.filter(status='publish', tags__name=tag) if tag else self.filter(status='publish')

    def get_tags_cloud(self):
        """统计所有已发布的博客中，每一个标签的数量(大于0的)"""
        tag_dict = defaultdict(int)
        for obj in self.get_publish():
            for tag in obj.tags.all().names():
                tag_dict[tag] += 1
        return tag_dict.items()


class Blog(models.Model):
    STATUS = (('publish', '发布'), ('draft', '草稿'), ('delete', '删除'), ('diary', '日记'))
    title = models.CharField('标题', max_length=255, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_author', verbose_name='作者', null=True, blank=True, on_delete=models.SET_NULL)
    image = models.ImageField('图片', upload_to='blog_imgs/%Y/%m/%d/', null=True, blank=True)
    slug = models.SlugField('(URL)别名', max_length=255, null=True, blank=True)
    status = models.CharField('状态', choices=STATUS, default='draft', max_length=10)
    content = models.TextField('内容')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    type = models.ForeignKey(Type, related_name='blog_type', verbose_name='分类', null=True, blank=True, on_delete=models.SET_NULL)
    likes = GenericRelation(Like, verbose_name='点赞情况')  # 通过GenericRelation关联到Like表，不是实际的字段
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('更新时间', auto_now=True)
    objects = BlogQuerySet.as_manager()

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super().save()

    def get_like_num(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'slug': self.slug})

apps/blogs/views.py
from django.views.generic import ListView, DetailView

from .models import Blog, Tag
# Create your views here.


class TagCloudMixin:
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'tags_cloud': Blog.objects.get_tags_cloud(),
            'blog_publish_counted': Blog.objects.get_publish().count()
        })
        return context


class BlogListView(TagCloudMixin, ListView):
    """已发布的文章列表"""
    model = Blog
    paginate_by = 5
    context_object_name = 'blogs'
    template_name = 'blogs/blogs_list.html'
    tag = None

    def get_queryset(self):
        return Blog.objects.get_publish(tag=self.tag) if self.get_tag() else Blog.objects.get_publish()

    def get_tag(self):
        self.tag = self.request.GET.dict().get('tag')
        return self.tag if self.tag in Tag.objects.names() else None

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class BlogDetailView(TagCloudMixin, DetailView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blogs/blogs_detail.html'
    is_like = False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_like'] = self.get_is_like()
        return context

    def get_is_like(self):
        if self.request.user.is_authenticated:
            like = self.object.likes.filter(user=self.request.user)
            if like.exists():
                self.is_like = True
        return self.is_like

templates/blog/blog_list.html
{% extends 'blog/blog_right.html' %}
{% load staticfiles %}
{% block left_css %}
    <link href="{% static 'css/blog/blog-list.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}blog list{% endblock %}

{% block blog_left %}
    <div class="in-left col-md-9 col-12">
        <div class="filter-items">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="type-items">
                        <div class="type-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle type-buttom" type="button"
                                        id="filter-by-date" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    date
                                </button>
                                <div class="dropdown-menu" aria-labelledby="filter-by-date">
                                    <button class="dropdown-item" type="button">near to far</button>
                                    <button class="dropdown-item" type="button">far to near</button>
                                </div>
                            </div>
                        </div>
                        <div class="type-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle type-buttom" type="button"
                                        id="filter-by-read-num" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                    read
                                </button>
                                <div class="dropdown-menu" aria-labelledby="filter-by-read-num">
                                    <button class="dropdown-item" type="button">more to less</button>
                                    <button class="dropdown-item" type="button">less to more</button>
                                </div>
                            </div>
                        </div>
                        <div class="type-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle type-buttom" type="button"
                                        id="filter-by-comment-num" data-toggle="dropdown"
                                        aria-haspopup="true"
                                        aria-expanded="false">
                                    comment
                                </button>
                                <div class="dropdown-menu" aria-labelledby="filter-by-comment-num">
                                    <button class="dropdown-item" type="button">more to less</button>
                                    <button class="dropdown-item" type="button">less to more</button>
                                </div>
                            </div>
                        </div>
                        <div class="type-item">
                                <span class="sort-span">sort：
                                    <span id="sorted_by">by date from near to far</span>
                                </span>
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="tag-items">
                        <label class="tag-item"><input type="checkbox" checked
                                                       value="false">all&nbsp;({{ blog_list | length }})&nbsp;</label>
                        {% for tag in tag_list %}
                            <label class="tag-item"><input type="checkbox"
                                                           value="false">{{ tag.name }}&nbsp;({{ tag.get_blog_num }})&nbsp;</label>
                        {% endfor %}
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-success btn-sm" role="button">clear up</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="blog-items d-none d-sm-block">
            {% for blog in blog_list %}
                <div class="card blog-item">
                    <div class="card-body">
                        <h5 class="card-title"><a href="#">{{ blog.title }}</a></h5>
                        <p class="card-text">{{ blog.content | truncatewords:"50" }}</p>
                        <div class="dropdown-divider"></div>
                        <p class="card-text">
                            <small class="text-muted">
                                <span></span>
                                <span class="glyphicon glyphicon-time"></span>
                                <span>{{ blog.created_date | date:'Y-m-d H:i' }}&nbsp;&nbsp;</span>
                                <span class="glyphicon glyphicon-eye-open"></span>
                                <span>{{ blog.read_num }}&nbsp;&nbsp;</span>
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <span>{{ blog.like_num }}&nbsp;&nbsp;</span>
                                <span class="glyphicon glyphicon-comment"></span>
                                <span>{{ blog.comm_num }}&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                {% for tag in blog.blog_tag.all %}
                                    <span class="glyphicon glyphicon-tag"></span>
                                    <span>{{ tag }}&nbsp;&nbsp;</span>
                                {% endfor %}
                            </small>
                        </p>
                    </div>
                </div>
            {% empty %}
                <p> ------ 暂无博客 ------ </p>
            {% endfor %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title"><a href="#">Card title</a></h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural
                        lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="dropdown-divider"></div>
                    <p class="card-text">
                        <small class="text-muted">
                            <span></span>
                            <span class="glyphicon glyphicon-time"></span>
                            <span>2018-02-05&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <span>1357&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span>63&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-comment"></span>
                            <span>999&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-tag"></span>
                            <span>python&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-tag"></span>
                            <span>linux&nbsp;&nbsp;</span>
                        </small>
                    </p>
                </div>
            </div>
        </div>
        <div class="blog-items d-sm-none">
            {% for blog in blog_list %}
                <div class="card blog-item">
                    <div class="card-body">
                        <h5 class="card-title"><a href="#">{{ blog.title }}</a></h5>
                        <p class="card-text">{{ blog.content | truncatewords:"50" }}</p>
                        <div class="dropdown-divider"></div>
                        <p class="card-text">
                            <small class="text-muted">
                                <span class="tag-span">
                                    <span></span>
                                    <span class="glyphicon glyphicon-time"></span>
                                    <span>{{ blog.created_date | date:'Y-m-d H:i' }}&nbsp;&nbsp;</span>
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                    <span>{{ blog.read_num }}&nbsp;&nbsp;</span>
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    <span>{{ blog.like_num }}&nbsp;&nbsp;</span>
                                    <span class="glyphicon glyphicon-comment"></span>
                                    <span>{{ blog.comm_num }}&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                </span>
                                <span class="tag-span">
                                    {% for tag in blog.blog_tag.all %}
                                        <span class="glyphicon glyphicon-tag"></span>
                                        <span>{{ tag }}&nbsp;&nbsp;</span>
                                    {% endfor %}
                                </span>
                            </small>
                        </p>
                    </div>
                </div>
            {% empty %}
                <p> ------ 暂无博客 ------ </p>
            {% endfor %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title"><a href="#">Card title</a></h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural
                        lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="dropdown-divider"></div>
                    <p class="card-text">
                        <small class="text-muted">
                            <span></span>
                            <span class="glyphicon glyphicon-time"></span>
                            <span>2018-02-05&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <span>1357&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span>63&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-comment"></span>
                            <span>999&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-tag"></span>
                            <span>python&nbsp;&nbsp;</span>
                            <span class="glyphicon glyphicon-tag"></span>
                            <span>linux&nbsp;&nbsp;</span>
                        </small>
                    </p>
                </div>
            </div>
        </div>
        {% if is_paginated %}
            <nav aria-label="blog pagination" class="mb-4">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Prev</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Prev</span>
                        </li>
                    {% endif %}
                    {% for page_num in paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active">
                                <span class="page-link">
                                    {{ page_num }}
                                    <span class="sr-only">(current)</span>
                                </span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Next</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}

{% block extend_js %}{% endblock %}

templates/blog/blog_right.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block extend_css %}
    <link href="{% static 'css/blog/blog-right.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap/bootstrap-3.3.7.min.css' %}" rel="stylesheet">
    {% block left_css %}{% endblock %}
{% endblock %}

{% block main %}
    <div class="row">
        {% block blog_left %}{% endblock %}
        <div class="in-right col-md-3 col-xs-12 d-none d-md-block padding-inside-0px">
            <div class="card mb-3">
                <div class="card-body padding-inside-15px">
                    <h5 class="card-title">
                        <span class="glyphicon glyphicon-book"></span>
                        Recommend
                    </h5>
                    <div class="card-text">
                        <p class="p-auto"><a href="#">it's my second blog-site, i will record result of self-study</a></p>
                        <p class="p-auto"><a href="#">my site build in python</a></p>
                    </div>
                    <br>
                    <div class="dropdown-divider"></div>
                    <h5 class="card-title">
                        <span class="glyphicon glyphicon-book"></span>
                        May you like
                    </h5>
                    <div class="card-text">
                        <p class="p-auto"><a href="#">site's front frame use bootstrap 4.0</a></p>
                        <p class="p-auto"><a href="#">site's backend frame use django</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="in-right col-md-3 col-xs-12 d-md-none">
            <div class="card mb-3">
                <div class="card-body padding-inside-15px">
                    <h5 class="card-title">
                        <span class="glyphicon glyphicon-book"></span>
                        Recommend
                    </h5>
                    <div class="card-text">
                        <p class="p-auto"><a href="#">it's my second blog-site, i will record result of self-study</a></p>
                        <p class="p-auto"><a href="#">my site build in python</a></p>
                    </div>
                    <br>
                    <div class="dropdown-divider"></div>
                    <h5 class="card-title">
                        <span class="glyphicon glyphicon-book"></span>
                        May you like
                    </h5>
                    <div class="card-text">
                        <p class="p-auto"><a href="#">site's front frame use bootstrap 4.0</a></p>
                        <p class="p-auto"><a href="#">site's backend frame use django</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extend_js %}{% endblock %}